#!/bin/bash
export PATH=/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH

#Start puma
cd /var/www/app/;/usr/local/rbenv/shims/bundle exec puma -e production -d -b unix:///var/run/app.sock -S /var/run/app.state
